let transcripts = [
    
    //1. some kinda robot
    "Oh, who is the guy that checks all his emails? That's me, Strong Baaad.","Dear Strong Bad,","Do you take your wrestling mask and boxing gloves off before you go to bed?","Sincerely, Abdi Larue.","San Diego, CA.","Well, that's a stupid question, Abdi.","Do you take off your face and hands before you go to bed?","And if so, are you some kind of robot?","And if so, what kind of powers do you have?","Do you use them for good, or for awesome?","Would you like to join forces?","I just happen to be the greatest criminal mind of our time.","Okay, until next time. Keep sending me your questions, and I will make fun of you... I mean, answer them.",
    
    //2. homsar
    "I'm gonna check my email all of the time, doo doo doo...","Hi Strong Bad,","If you hate Homsar so much, why don't you kill him?","-Vinnie C.","You know what, Vinnie? You're right. I'll be right back.","Hey, Homsar!","Uhdyeah, what ees eht, Stwong Baaaaayaad?","Oh man, Vinnie.","That feels so much better","Thanks a lot!","Okay, so until next time, keep sending me your questions, and I will keep making fun of your punctuation and spelling.","I mean, answer them.",
    
    //3. butt IQ
    "Checkin' my email, checkin' my email, checkin'-checkin'-checkin'-checkin' my email.","Dear Mr Bad,","How do you know if someone's butt is stupid?","I mean, is there like some kind of IQ test?","Crapfully yours,","Tyler.","Oh, come on Tyler!","Don't you remember your algebra, man?","It's called the Transitive Butt Property.","And it clearly states that the stupidity of somebody's butt is greater than or equal to the stupidity of that person's head.","So, take our friend Homestar Runner for instance.","Look at his stupid head!","Look at how stupid his head is.","Okay, so you can easily infer from this that because he has such a stupid head, that easily his butt is going to be at least as stupid if not stupider.","So there you have it.","Okay, so until next time, on a scale from one to awesome, I'm super great.",

    //4. homestar hair
    "I check the email once, I check the email twice, doo doo doo, doo doo doo...","Okay, let's see what we got here...","Homestar Hair.","downloading...","Home...star...Hair...?","What the...","Oh man!","I swear if I get another one of these freakin' 'Hairstyle Runners' from one of you guys, I'm gonna have to start busting some heads, okay?","I mean, how come you people never play my game, man?","I never get any Strong Libs in my email.","I mean, there's this whole game out there that's all for me that you guys can fill out, you know, and like, send me some hilarious crap or something.","Now you got me all cheesed off!","I'm gonna play some 'Temple of Apshai'.","Forget you guys.","Oh, my hit points are, like, inexcusable in this dungeon, man.","I need to find some elixir or something.",
    
    //5. making out
    "Checkin' emails is like the best thing I do.","Dear Strong Bad..,","Do you like making out?","Because my boyfriend won't.","Mostly because he's jealous of you.","I've tried the whole Peter Frampton thang, but nothing seems to work out.","Please help me Strong Bad...","Kissless in Santa Rosa.","Well, Kissless, you're going about it all wrong.","Frampton's not going to loosen anybody's lips.","If you really want to make out with this guy, you need to go straight to the master of make out rock himself... ME!","So here's what you do.","You wait til he comes home, then light a few candles and maybe have a glass of wine.","And then put on my hit single 'You're Really Ugly (But There's Nobody Cute Around).'","I'll tell you what, he'll be all over you like the King of Town on a Chinese buffet, man.","All right, so until next time send me more questions.","SEND ME MORE QUESTIONS!!!",

    //6. depressio
    "I check, you check, we all check for e... mail check... an email...","Dear Strong Bad,","Tell Strong Sad he is dumb and a crappy guy.","Your fan, Anthony.","from South Gate CA.","Hey, stupid! Do you know some guy named Anthony from South Gate?","Oh yeah. I was just making him this card—","—and gonna send him a hundred dolla—","Yeah, well he says you're dumb and a crappy guy.","Ohh...","Look Anthony, as much as I like insulting my stupid kid brother, I'm not your freaking message service, alright?","Next time, you email him yourself.","His email address is: depressio@homestarrunner.com.","Okay, so until next time, 'Everybody email that guy!'","'What guy?'","'ME!'","'Everybody email that guy!'","Hello there,","I hope your email wasn't full of awful, hurtful remarks like all the rest but I'll never know.","I stopped reading emails a long time ago and wish my brother would stop giving out my address.","Before you start making fun of me again, I'd like to share something with you.","I hope this puts us on the same page of this dusty, many volumed set of ever-changing encyclopedias we call Life.","Strong Sad is no longer accepting emails because you people kept signing me up for 'natural male enhancers.'","That, and the death threats weren't very cool either.","Leemee 'lone!",
    
    //7. halloweener
    "I am going to check my email.","Dear Strongbad,","I want to have the bestest halloween costume ever this year.","How can I make a strongbad costume?","With crap,","Ben from Ohio University.","Well Ben, I couldn't agree with you more.","You dress up like me this year and the ladies will flock to you like the Poopsmith to an overflowing toilet.","But I digress. Onto the costume...","We'll demonstrate on stupid over here.","Hello!","First, paint your head red.","Then, take your shirt off... to expose your manly chest.","Oh!","Next, get some boxing gloves,—","—or if you don't have boxing gloves, oven mitts will do.","Next, duct tape some aluminum foil—","—to some twine.","And finally, get your mom to make you a Strong Bad costume.","You'll be the belle of the ball.","I'm a belle!","Okay, so until next time, who put the 'ween' in 'Halloween'?","I don't know.","Probably you.","...you freakin' weirdo!",

    //8. brianrietta
    "I remember the time when I checked my email.","Dear Strong Bad,","Every time I watch a cartoon with you in it, I can't help but realize how incredibly gorgeous you are.","I love the way you walk around without your shirt on so confidently.","Anyways, I was wondering if you would like to go out sometime.","Give me a call, Pom-Pom has my number.","Hopefully yours, Brian.","Oh, well, Brian, maybe you and I could— uh— hey... BRIAN!?","What the crap?","Look, man.","Unless Brian is short for... Brianrietta or Brian-Sue or something like that, it's just not gonna work out between you and me, okay?","Sorry to crush your hopes and dreams, - Strong Bad.","Okay, so until next week...","1, 2, 3, email me!","1, 2, 4, email me more!",
    
    //9. i love you
    "I've carefully set aside this time for checking my email.","i love u.","-fhqwhgadshgnsdhjsdbkhsdabkfabkveybvf.","Look, fhqwgadshg...","Can i just call you fhqwhgads?","Look fhqwhgads, I'm sorry to say, but the feeling's not mutual.","Mainly because of your long freakin' name.","I mean in the time it took me to say your name, I coulda done all kinds of stuff.","Like paint a picture of a guy with a big knife.","Whoa, in fact, I'm gonna get started on that right now.","Oh yeah!","This is looking great.","I mean, I think I could probably sell this at like the arts and crafts fair, you know... to maybe some POWs, or, like, somebody's dad...",

    //10. trevor the vampire
    "I'm totally checking my email.","Total, man.","Hi strong bad.","This is Trevor from Hampden Maine and I was wondering if you could teach me how to be as awesome as you.","I am a vampire and...","And what?","That's it?","I'm a vampire and here's a million dollars...","or I'm a vampire and here's your own spaceship...","I mean what the f-","Oh no, I get it.","THEY GOT HIM!!!","Somebody stuck him with a stake through the heart!","Oh, this is so sad!","Oh Trevor, I pine for you.","Hi, everybody.","In memoriam of poor Trevor, let's go back and revisit a few of my favorite Trevor memories.","This is Trevor from Hampden Maine and I was wondering if you could teach me how to be as awesome as you.","Oh, that was great. And who could forget this one?","I am a vampire and...","And what? That's it?","Ah, we sure had some great times Trevor.","In Memoriam -Trevor-","I'm gonna miss you, bro.",

    //11. i rule
    "Email, grumble grumble, email, grumble...","If you are so evil, how come you don't rule the world or at least some kind of field?","Mike, UK.","What are you talking about, Mike, UK?","I mean I've totally ruled that field out behind the dumpsters since like diaper school, man.","Aaaah, my kingdom continues to flourish. Uh, carry on, everyone.","Hey!","The Cheat!","What, you wanna get banished? Don't touch that!","What're you standing around for, man?","Don't you have, like, some of my bidding to do?",

    //12. credit card
    "Initiate email check in five, four, three, two, one.","Dear Mr. Bad,","We regret to inform you that your credit card has expired.","To keep your account, we will need you to send your old credit card number and expiration date, as well as a new one so we can make the change.","We promise we are real and not just trying to steal your money.","John, and some other people who aren't scam artists.","Whoa, this sounds pretty serious. I know just what to do.","Just a little of this...","Ooh, maybe a dash of that...","Okay, let's see what we got here...","Dear Superfied Credit Union,","You've got the same e-mail address as my friend Strong Bad!","Anyway, here's my credit card information:","That was too easy, man.","Well, it looks like Homestar is about to make a little contribution to the Lots of Awesome Stuff for Strong Bad Fund.","Gimme one of these...","A couple of these...","Oh, everybody needs one of these...","Oh, this thing, I gotta have that...",

    //13. i she be
    "Email, dud-duh-doo-duh-dud-duh, dud-duh-doo-duh-dud-duh...","hey my name is great looking girl strong bad!","i she be your girlfriend.","Uh...","Hey!","My name is Strong Bad, great looking girl!","I he be your boyfriend.","Okay, seriously. All i gotta say about this is...","GET IN LINE SISTER!!!","I mean, do you know how many freakin emails I get like this a DAY?","From ladies with proper grammar?","I mean come on!","A guy's gotta have some standards right?","But, I do feel kinda sorry for you, so I won't let your email go to waste.","Okay, so tune in next time: Same Strong Bad time, same Strong Bad channel.","are you around, clown?","sure am, sam.","LOL!!! :-*.","i want us to meet in person.","OMG!","where?","the food court?","sbarro.","8pm.","whatta you look like?","6ft tall.","buff.","big red 'M' on my chest.","no neck.","can't wait.","L8r.",

    //14. duck pond
    "Must... check... email...!","dear strong bad,","do you ever feed the ducks?","personally i think feeding the ducks is the greatest thing in the world.","what are your thoughts on this subject?","your friend,","ron kiwi.","Unfortunatley, Mr. Kiwi, there are no ducks by my house.","But I do have a pretty sweet duck pond simulator for my computer.","Check it out, man.","Wow, you're right, Ron.","This is the greatest thing in the world.","I mean it's like I'm right there at the pond.","Come here, ducky.",

    //15. the basics
    "Everybody... check your email...","Dear strong bad,","how do you do it .","teach me some of your trick's.","With crap,","T.J.","Well, I mean I can't tell you all of them TJ, But, you know, there's the basics.","I mean, like if somebody's like, 'Hey! Are you listening to me?'","You say, 'Yes,' but you know you're not really listening.","Um, then there's the one where you say, 'Hey! Look over there.'","And when they turn their head, you know there's nothing there and you pour some Coke down their shirt.","And this one is a little amateur, but it has worked for me in the past.","You know, you bet somebody a hundred 'bucks', and if they win, you know, you'll... you give them like a hundred kicks in the butt and you say, you call that a buck.","I mean, I don't know, somebody invented that...and...it works pretty good.","You get to kick somebody.","But everyone has a different taste, you know?","Develop your own style, TJ.","Reach down inside yourself and pull out something...y'know, not like...organs.","You know what I mean.","Anyways, email...","Oh, there'll be another one next week...",

    //16. band names
    "Who's that giving Strong Bad a hand?","Email... Email...","hey strong bad,","help us come up with a name for our band.","i was thinking about 'invisible robot fish' or 'for good or for awesome.'","hurry up please, we have our first show tomorrow. you rule.","- dan.","Well, Dan, the easiest way is to, you know, just have a really cool last name and use that.","You know like Van Halen, or Dokken, or to a lesser extent... Z'Nuff.","And then the other way is to take a really cool word but then spell it all wrong.","You know like... 'LAZOR' —","—or 'BIGG NIFE'—","Well, all right!","—or something like 'TARANCHULA'—","—or maybe like 'LIMOZEEN'.","You know, these are all—","—great names.","And you know, go ahead and take them.","I'm not going to charge you or nothing.","Just, uh, put me on the guest list plus one for that show huh?","I'll probably take Pom Pom.","You know, He's been pretty cool lately.","Okay, so tune in next week, when my guests will be Lemmy from Motörhead and the guys from Krokus!",

    //17. studying
    "Ohh!","Electronic mail!","Dear Strong Bad,","My girlfriend is really annoying because she calls me when I'm trying to study.","What should I do?","Crapfully yours,","Roy.","Oh, well!","I think I might have a little piece of advice for you, Roy.","Close the book and quit being such a dork-on!!!!!!!","I mean, this girl obviously has the hots for you man.","Why do you think she's calling you?","I mean, you've got the potential here to get 1st, 2nd, and quite possibly even 3rd base.","So unless you're studying a book called 'This Book is Better than 1st, 2nd, and Quite Possibly Even 3rd Base', I suggest you hightail it over to your girlfriend's house ASAP, man!","And also, send me a copy of that book.","Because this sounds pretty good.","You know what...scratch that.","You keep studying Roy, I'm going over to your girlfriend's house.","Um, I forgot.","I don't know her name or where she lives, but your girlfriend still loves me, Roy.",

    //18. stand-up
    "Something has compelled me to check my email.","dear strong bad,","ur a real, funy guy.","have you ever done any stand up comidic stuff?","crapfully crappy,","joe p.","What?","No.","No.","No.","I mean, no.","Never.","No.","What?","No.","Psst.","Come with me.","Once again, thank you to little Marzipan and her wonderful clogging.","Okay, so up next we got the comedy stylings of little Strong Bad.","Thank you, Coach Z, for not patting my butt.","Good evening, ladies and germs.","Um... How about this cafeteria food?","Is it cardboard or is it pizza?","You know, 'cause it... tastes bad.","Um...","What about that one... that joke...","Coach Z's hair is funny looking.","Don't you guys think?","'Cause it's big...","He has really big hair...","Oh no!",

    //19. tape-leg (1)
    "Ow-mnow, mnow, mnow...","Mow-mnow, mnow, mnow...","Dear strong bad,","my brothers are always telling me that your legs are made of tape, is that true?","-Nicolas.","Nee-co-las.","They said my legs were made of tape?!","WHAT??","I mean, do I look like some kinda tape-leg?","I can guarantee you, man, I am not a tape-leg.","I mean, look at this leg.","Look... look at it there...","Oh wait a minute, what's that on-","OH, there's a little piece of tape on my shoe!","That's what they were probably talking about.","Yeah.","You probably misunderstood them, man.","No, they probably said I had tape on my leg or my shoe and you thought they said that my leg was made of tape.","My leg is not made of tape.","Pfffph!","I must've just stepped on an innocent piece of tape...tape.","All right, so until next week, send me some good ones.","You know, some good ones.",

    //20. spring cleaning
    "Hello, everybody!","This week it's time for some spring cleaning.","Ready? Go!","Dear Strong Bad,","Why do you hate Homestar so much? He seems like a nice guy to me.","Caitlyn.","Oh, what a good question!","Let me think about how I should answer that...","DELETED!!","Ah ha ha, that felt great.","What's next?","Do you have a secret crush with marzipan?","steve, sterling, VA.","Ah, now this question is definitely worth my time and consideration—","DELETED!!","Uh ho ho, this is getting good!","Dear Strong Bad,","How do you type with boxing gloves on?","Mike, Bend Oregon.","Oh, that's a new one.","No way do I get this freaking question all the time.","I suppose I'll probably answer it right now—","DELETED!!","Oh, who's next man?","Dear Strong Bad,","Are you made of crap?","Did you invent the word crap?","Where did the word crap come from?","Crapfully crapfully,","Chad.","Oh, I'll totally answer this one because apparently the only thing I'm concerned with is the word crap—","DELETED!!","Oh, I'm on a roll!","Strong Bad,","Your last email was pathetic.","I was disappointed.","Come on, you can do better than that!","This is like the highlight of my week.","Suprised at your lack of humor,","DELETED!!","Ahhh!","I feel so cleansed.","So fresh and so clean, clean.","Okay, so until next time, ain't nobody dope as me.",

    //21. cartoon
    "This episode, Strong Bad checks his email.","dear mr bad,","make a cartoon with only u in it and then just u do the commentary.","crapful,","geroge.","Oh, no way, Geroge.","We tried that once.","Trust me, man.","Bad idea.","Umm...","So this is another part where it's just me.","And I'm kinda standing around.","You know, just standing.","I guess I don't do very much.","No wait, I just scratched my head.","Yeah, I remember that part.","I totally had to scratch my head then, man.","I can't remember exactly what I was looking at there.","Er, I think it was like a bird, or maybe a cloud that looked like a bird.","You know, like a bird cloud.","I dunno.","That wasn't so bad actually.","You know it's like, All Strong Bad, All the Time!","But you know what they say,","'Too much of a good thing is an awesome thing.'","'But too much of an awesome thing is...umm...really, really dumb and bad.'","All right, so until next time send me a little email and I'll give you a little crap.","So, this is where I just finished checking my email and I'm just kinda sitting there.","You know, I...","I think I was probably staring at my computer screen.","You know, watching those green lines go by.","I'd be like 'Whoa, check out these green lines!'","You know, they just keep going.","Those things could hypnotize you, man.","If you watch them long enough.","Oh, see!","There I go.",

    //22. sb_email 22
    "Do, du, dadada do, du, dadada do...","Hi Strong Bad,","I'm from England.","What do you think of the English?","Thank you,","Mark.","Uh, gee, Mark, if you're really from England, shouldn't you have some kinda unnecessary vowel at the end of your name?","And what is this 'Thank you'?","Whatever happened to 'Cheers' or 'Cheerio' or 'Nevermind the Bullocks'?","Call yourself 'English'.","But, anyways, what do I think of the English, huh?","Oh, I'll tell you what I think of the English!","In this Monday's edition of U.S. based 'Strong Bad Email,' the title character, Strong Bad, an odd little bloke with a Mexican wrestling mask for a head and boxing gloves for hands made such comments that warranted the Queen to ban the edition from UK shores.","Strong Bad has been charged with 'verbal crimes against the crown' and the Strong Bad Email, now simply being called the infamous 'sbemail22,' has been removed from broadcast in both the UK and the States.","At a press conference held on Tuesday,","Strong Bad, how do you respond to claims that your comment brought the entire royal family to tears?","Screw all y'all.","Cor blimey!","I can't believe he said that.",

    //23. little animal
    "Oh!","What's this?","An email?","For me?!","What would you do if a little animal came up to you.","crapfully yours,","Ashley and Anthony.","Um, I don't really know.","Let's find out.","Oh, The Cheat!","Come here for a moment!","Ummmm...","So, there's your answer.","A little animal comes up to me...","I'd kick it.","Okay so until next week, everything is awesome an—","Oh, er, hey big guy.","Er, you know, I's just kicking The Cheat.","Er, it's a little joke.","You know we got the people watching at home.","Just trying to be kind of funny for 'em, with the joke.","A joke-kick...","I'ma kick you, too!!","RAAAAH!!",

    //24. the bird
    "So I was like, 'Well, you think you're so hot, but me hot, me hot!'","Bubbles.","Yeah, that's a pretty good one, huh?","Oh crap, I should probably check my email.","Hey, let me see your Pom Pilot!","Checkin' my email...","Here at the stick...","That's pretty cool...","DEAR STRONG BAD,","IS IT HARD TO FLIP SOMEONE OFF WiTH BOXING GLOVES ON?","VERY CRAPFULLY:","PHYLO D.","Uh, not really, man.","I'm flippin' you off right now.","Of course there's other ways to give somebody the finger.","Oh, check it out: behind the back.","Oh, around the world.","And my personal favorite.","Psssshhh!","The Double Deuce!","What's your favorite, Pom Pom?","Ah, Pom Pom likes the Single Deuce.","Hey, Homestar!","Hey, right back atcha, Strong Bad!","He just gave me the bird!","Bubbles.","That wasn't funny, man!","That'll hurt a guy's feelings.","Okay, so until next week, send me your email.","I will more than likely flip you off.",

    //25. super powers
    "Strong Bad Email is filmed before a live studio audience.","Is that blue diamond kinda thing on your forehead the source of all your superpowers?","Or is it merely decorative?","Aaron C.","Well, sorta, Aaron.","But see, there's only one power.","Though I guess it is pretty super.","Check it out.","So, there you go.","It's not much, but as you can imagine it's a big hit with the ladies.","And so far I've only found it works with cold ones.","But come to think of it...","Oh, I'd definitely say it's just a result of tight pants.","Oooohh, tight paaants!","Oh!","Sorry about that. What were we talking about?","The tightest of pants.","Oh, right, right. Tight pants.","What the -?","Are you okay there, Homestar?","I don't know. Is my head getting bigger?","Once again, I point the blame squarely at tight pants.",

    //26. CGNU
    "Check that email, check it down, check that email, smack it around.","dear strong bad,","i want to be a graduate of Crazy Go Nuts University, just like you.","Please let me know how i can accomplish this goal.","thank you.","Margo.","I'm glad you asked me, Margo.","Do you want to be more awesome?","Sure!","We all do.","Here in Crazy Go Nuts University, you can get the experience you'll need to be almost half as awesome as I am.","Get your certificate in:","Cheesing People Off,","Indian-Giving,","Cutting Ones,","Doing Some Other Things,","Home Invasion,","Cracking Wise,","World Domination,","Sending Me a Dollar,","Total Spaceship Guy,","TV / VCR Repair,","or GET YOUR DEGREE!","Applying is easy, just take this free art test.","Fill out the test and send it back to us.","And you will be well on your way to a better, awesomer you.","Remember, at Crazy Go Nuts University, the future is. . . you.","Probably.","Actual applicants not accepted.","Art test is only so we can make fun of you.",

    //27. 3 wishes
    "I got an email.","I got an awesome email.","Dear Strong Bad,","If you had three wishes, what would the second one be?","Much Crap,","Brandon Hofer.","Judson College, Elgin, IL.","Geez, I didn't need your freaking life story, man.","Ohh.","That's an easy one Brandon.","Horns.","No question.","I'd wish for a pair of horns.","Here, check it out.","Look at how great I would look, man.","So majestic, yet so wicked awesome.","Like I could maybe go on tour with some heavy metal band and like be their mascot you know and come out on stage, and have some type of laser fight with the lead singer and all the fans will go nuts.","Oh man, that would be great.","Okay you guys, so until next week, it's not required that you sign your email, 'Crapfully yours,' or, 'With a bunch of crap,' or, 'Crap in the times,' or, 'Crap is so great,' 'Everything is crap,' 'My middle name is Crapperson.'","You know, you could just put, 'Sincerely'... or, 'Yours truly,' is another good one.","Come on, guys. I'll still read 'em.","You know these horns kinda look like croissants the way I drew 'em.","Maybe my third wish will be for a couple of croissants.","Yeah, like, heated up with some butter melted on the top.","I gotta get The Cheat to get me some of those...","Some of those... croissants.",

    //28. 1 step ahead
    "This one better be good, man. I got a lot of money riding on this one.","hello strong bad,","don't you think it would be funny if you glued strong sad's hands to his face?","I think it would be...","alex,","medford, nj.","I'm one step ahead of you, Alex.","CHOOSE YOUR OWN STRONG BAD EMAIL ADVENTURE.","Should Strong Bad really glue Strong Sad's hands to his face?!","If you choose YES turn to page 93.","If you choose MAYBE turn to page 121.","If you choose to TAKE IT IN A BIT OF A DIFFERENT DIRECTION turn to page 146.","Guys?!","Owww!","Oh!","Ohw!","Augh!","Okay, you guys!","Augh!","It's not funny.","Augh!","I'm kinda...","Augh!","...unable to defend myself.","Oww!","Oh!","More so than usual.","Oh!","O-Ohw!","Augh!","Augh!","I'm blind!","My prayers have finally been answered.","Oh wait, my hands are just glued to my face.","Oh well, I'll take that.","Oh man, he likes it!","Okay, go to plan B!","Though I decided to take it in a bit of a different direction.","Oh, hohoh...","Oh, hey, Homestar!","Er, Strong Sad.","Why are you touching your buttocks?","That's pretty weird.","I can't help it!","Okay, that's really weird.","No, wait, you don't understand!","Grabbing your butt?","That's not very ladylike.","I'm not a lady.","Oh!","Whatever.","Augh, this is getting frustrating!","Oh, Strong Sad.","Fancy seeing you here!","And uncontrollably grabbing your own butt, I see.","Oh, don't let me get in the way.","Carry on!","Please, come back!","'Attaboy, Strong Sad.","Hey, where are you going?","You have any solvent?","Or Goof Off?","Or Didi Seven?","Somebody get my hands off my butt!",

    //29. superhero name
    "All these... emails... I don't understand.","Dear Strong bad:","Why is it that your superhero name does not end in 'man' just like Superman, Spiderman. etc, etc...","Your friend,","Stiny.","Umm...I don't think you're in a very good position to be criticizing people's names, STINY!!","I mean, what kind of a name is Stiny anyways?","It sounds like some supervillain's little sidekick, that he's always ordering around you know.","Like, 'STINY! GET ME A DANISH!!'","Or 'STINY! WHO SPILLED COFFEE ALL OVER THE PLANS FOR MY DEATH RAY?!'","Stiny...","Naw, you know what?","I'll change my name to Strong Badman if you agree to be my sidekick: Li'l Stiny.","And you can wear a little mask and a little cape...","Hey The Cheat...","Er, just doing an email.","What?","No!","Of course you're still my sidekick!","Yeah, that cape looks great on you.","Look, I was speaking hypothetically.","{irritated The Cheat sounds}","Oh come on, don't give me that!","{loud, angry, The Cheat sounds}","Ah, The Cheat!",

    //30. 12:00
    "I'll take Strong Bad Emails for a thousand, please.","Strong Bad,","My vcr keeps blinking 12:00 over and over.","Do you have any suggestions on how to fix it?","Thankyou,","Cory Dewey-Smith.","I had the same problem, Dewey-Smith.","So I called in a professional to get the job done.","Let's go see how he's dewing...um...doing.","So, Bubs, how is it coming?","Oh, hey, Strong Bad.","I think I'm almost finished.","It took me a little while to figure out what I was going to do.","Then I duct-taped an alarm clock to your VCR.","Duct-taped an alarm clock to the VCR...","See, I never would have thought of that!","Okay, there's some hairs that seem to be stuck in the duct-tape here.","Was that on purpose?","Oh... No!","That's just left over from my first idea, which was to duct-tape The Cheat to your VCR.","He wasn't into that.","Oh, I could have told you that, man.","Well, anyways, thanks for your help, Bubs.","And thank you, Cory... Dewey-Smith!","So... Join us next week when we'll be duct-taping clocks to all kinds of different stuff.",

    //31. sugarbob
    "Umm... I don't know... I'm gonna check my email.","DEAR STRONGBAD,","MY GIRLFRIEND WON'T TALK TO ME ANYMORE BECAUSE SHE IS IN LOVE WITH YOU.","I DON'T KNOW WHAT TO DO, MAYBE YOU COULD TELL HER THAT I AM COOL AND YOU ARE TAKEN.","SINCERELY,","YOUR JEALOUS FAN,","DANIEL.","Number A, you don't have to shout.","Do you know how many Internet etiquette laws you're breaking by typing in all caps like that?","Well, you're breaking one: Don't type in all caps.","Anyway, sure Daniel, I'll tell her.","Put her on.","Dear Daniel's girlfriend, maybe I should tell you that Daniel is cool.","And that I am taken.","Yeah... Yeah...","Taken by a whole buncha girls that are way hotter than you, baby.","So sorry sweetie, tootsie-pie, sugarbob, funky bunch.","Anyways, they're all right here.","Uh...","They're climbing all over me.","Um, say hello, ladies.","Hi!!!!","g2g!!",";)","What's up??","Strong Bad roxors!!","lmao!","_^.^_","I'm way prettier than you.",":P","ThuggaChik48031 in tha hizzy.","SB is the shizzle.","p's.","So as you can see, they're all really nice, and hot and very web savvy.","So you don't have a chance with me, sugarbob.","You might as well just stick with Daniel over here.","I can't see you doing any better.","Okay, put Daniel back on.","Okay, Daniel, it's all taken care of.","Though I'd probably buy her some stuff and start working out just in case.","I am quite a catch.","Okay, everybody.","Bye.",

    //32. flag day
    "Riballa diballa check email.","Hey Strong Bad,","Happy Flag Day!","I bet you have a totally awesome flag for Strong Badia.","You should share it with us.","Your pal,","Pablo Phoenix.","Oh, you sound like some kind of popstar, man.","Look Out Ladies Production presents: Pablo Phoenix, this Friday at the civic center.","Anyways, Pablo.","Happy Flag Day to you too, man.","It just so happens Strong Badia has about the coolest flag you ever saw.","Would everyone please rise for the presentation of our national colors.","Oh...","Oh, I like that!","Oh yeah!)","Come to the place where tropical breezes blow.","Come to the coolest place I know.","The people are so great,","But really there's only me,","And that means I'm so great,","And also there's The Cheat.","Oh there's The Cheat...","in the place where the tropical breezes blow.","The Cheat in the coolest place I know.","The ones are always cold,","And the parties last all night,","And there's probably lots of chocolate,","And population tire.","Population...","Ti-i-i-ire...",

    //33. gimmicks
    "Super great, super great...","Check your email!","Diggity...","Dear Strong Bad,","Do you remember when you would answer emails and be funny without some sort of gimmick?","I do, I miss those days.","With a lot of crap,","Mike W.","Everett, MA.","Yep.","I remember those days, Mike.","Those were good days...good days.","What the... crap?","Whoa!","Whgjht?","Oh, geez! Are you okay?","What, yeah, no, I'm fine!","Nothing happened; I'm fine!","Did your terrible computer explode?","No, shut up!","Look, I'm gonna need to borrow, like, nine hundred dollars.","Well, I hope that's for a new computer.","You could get one like yours at a garage sale for, like...fifteen dollars.","I said shut up!","I liked that computer.","I hope some of that money's for buying me a new poster.","You don't seem too broken up about that.",

    //34. weird dream
    "Out of the way, The Cheat!","I gotta use your computer.","Time to check the email...","Time to check the email...","TIME... TO... CHECK...THE... EMAIL!","Uh, The Cheat, I'm having some problems.","{annoyed The Cheat noises}","Your computer has too much computer in it and not enough typewriter.","Okay, here we go.","what is the weirdest dream you've ever had?","-marie.","Okay, Marie, I'll tell you, but you gotta understand...","The day before, all i had to eat was like...13 pudding pops, okay?","So the whole dream was just a picture of...","Well, lemme show you.","{surprised The Cheat noise}","The United States in tight, White Brand underdrawers.","Briefly, let's discuss what this dream means.","No, really, you guys can interpret this one how you want.","Me, I blame the pudding pops.","Okay, so...","Maybe I shouldn't have shared that with you guys.","Uh... See you next week.","How's it going, Texas?",

    //35. sisters
    "Ah, the old girl's working again.","What do you got for me?","Strong Bad,","My sister and me think you are so cool.","Do you have a girlfriend?","There is two of us.","Yours,","Ali.","Ohh, there's two of them!","Well, Ali.","There's one of me...","DELETED!!","A-deleted...","DELETED?!","What?!","Oy, what happened?","No!","Undeleted!","Undeleted!","I didn't mean to do that!","Awwww, man!!!","Come back, Ali!","Come back, Ali's sister!","You two meant everything to me!","Okay, calm down.","Maybe she'll email me again.","I'll just... hang out here for a while and try to picture which one of them is hotter.","Ali or Ali's sister.","Ali...","Ali's sister...","Ali...","Ali's sister...","Oh, there she is!","Okay, here we go.","hello,","I am write single to salute and wait for answer again.","What?","You're not Ali.","You're not even literate.","Oh!","Though, I have just the thing for you...","DELETED!","SAVED!!","Oh, that's great.","Great, thank you.","Yeah, go ahead and save that one, why don't you, yeah.","So I can treasure it for years and years, and show it to my kids.","The ones I should be having with Ali and Ali's sister!","I hate this computer.",

    //36. guitar
    "Oh, tap your toes and check your email, oh a-tap your toes tonight...","Hey Strong Bad whats up?","Can you play the Guitar?","Derek Highet.","Northern California.","Hey, Derek.","Not much, man.","Yeah I can play the guitar.","I know all about virtuosos and trembalos and arpeggios.","I can do it all.","I can play your basic rhythm guitar, like...","Jug jigga jug jigga jug jigga jug jigga jug jigga JAH JAH, jiggidy jug jigga jug jigga jug jigga jug jigga jug jigga JAH JAAH!","You know, something like that.","I can also play some pretty hott lixx, too.","You know the kind that are just way up high on the tiny strings and you mash your fingers on 'em.","Meedley meedley meedley meedley meedley meedley meedley meedley meedley meedley meedley meedley MEEEEEEEEEEEEEEEE.","Yeah, yeah and then Strong Mad comes in on his bass and he's like, dou dow da dou da da DOU da dou da dou dou dou.","And The Cheat comes in on his keyboards and he's like, boop boop boop boop boop boop boop boop boop boop boop boop boop boo.","And then I'm like 'And the dragon comes in the NIIIiiiiIIIiiiiIIIIIIIIiiiiiiiiiiiIIIIIIIIiiiIIGGHH—'","Augh... Oh yeah!",

    //37. dullard
    "Mmmmm... fresh emails...","Strong Bad,","How do I deal with the office dullard?","Jason.","I'm glad you came to me, Jason.","The office dullard is a clever foe.","But there are ways you can beat him.","Here are a few of my tried and true methods.","Hey man, what's up?","Good time, bad time...?","Oh!","Oh, oh!","Yes, yes, yes...","Uh, so no, I'm still here, yes.","Working hard.","I've been synergizing all morning...","I'm not going to be able to talk right now, man.","Right...","Yes...","Multi-tasking...","Once I finish my second run, you know, I'll have a smoothie or something, and then I head to the gym, and do, I've been doing about three sets of reps a piece, and then one...","Psssh!","Yeah... So, how much can you bench?","So, did you catch last night's episode of Popular Reality Show?","Yeah?","No?","You missed a good one, man, you missed a good one!","They were kickin' people off left and right, and, like, some people got kicked on, and um, I mean, it was... you shoulda watched it.","You definitely shoulda watched it.","Should-a watched it.","I mean, they'll be talkin' about this one for a while.","I mean, I'm going ta be talkin' about this one for a while...","Oh, cool, I guess you're going to go watch it now...","Oh, all right, man...later...","Cool...","So the next thing I know...","Yeah.","...Fredrickson from accounting comes up to me, puts this...","Yeaah.","...thing on my desk, I'm like, 'Hey man, the mailroom is...","Oh yeah.","that-a-way,' you know, so I sent out a memo, like...","Oh yeaaah.","...to everybody.","Yeah... yeah... oh yeah...","Yeah... mmhmm...","So there you go, Jason.","One of those ways should work.","Though it couldn't hurt to steal his lunch from the break room fridge everyday.","Mmmmm... Hot Pockets.","I need this on my desk by five.","I need this on my desk by five.","I need this on my desk by five.","I need this on my desk by five.","I need this on my desk by five.","It's five.",

    //38. helium
    "Emaillll eeeemailll eeemmailll...","Dear Strong Bad,","What do you sound like when you breathe helium?","Shack.","Whittier.","Oh I dunno, Shaq.","Oh I dunno, Shack.","I haven't done that in a while.","Though I think we have some leftover balloons from a party we threw last night.","Lemme see.","Hey guys! How do you like my sounds?","Pretty great, huh?","I sound like...one of the Golden Girls.","Or, like, some type o' guy who might... sing a song.","You know like, 'Welcome to the High Voice Crew!'","I hope you have a high voice, too!","When you've got a high voice, you don't have a choice, your voice is high all the time.","Welcome to the High Vo...","Oh, I guess... I got kicked out of the High Voice Crew.","MEEEE.","MEEEEEEEE!","THIS IS MY FUNNY VOICE!","THIS IS MY FUNNY VOICE!!!","Yeah, that's a pretty funny one, big guy.","Aagghh... I've got a wicked head rush.","So from then on, it was pork and beans.","I don't know if that's entirely healthy.","Whoa, Marzipan.","Check out that ugly bird.","Homestar, I think that bird is The Cheat.","No way!","The Cheat is one fine-looking young man","That is an ugly bird.","I'm sad that he's flying.",

    //39 property of ones
    "Gimme some of this and gimme some of thiiiiis...","Gimme some of this.","Hey Strong Bad,","How's it hanging?","Last weekend I almost drank a one that was not cold.","Has this ever happened to you?","Dan Waters.","Dallas, Tejas.","Aw, Dan, you dodged a bullet, man.","Because lemme tell you...","A One that is not cold, is scarcely a One at all.","Allow me to demonstrate with one of my bogus mathematical theorems.","I call it 'The Property of Ones'.","It goes like this: The ONEitude is directly proportional to the Colditude of the ONE.","So you got that, Dan?","The colder it is, the more of a one it is.","Because you don't want to end up with a Cold None.","I wouldn't wish that on anybody.","But now in foreign lands, they've been known to drink Not So Cold Ones, Room Temperature Ones, and even Warm Ones.","Whoa!","But where I come from, it's CUH-HOLD ONES.","Though I have to admit, on certain evenings in late spring, a Cool One can be very refreshing.","Ooh... That's a good One.",

    //40. vacation
    "Oooh, duh doo doo doo, my email left me, duh doo doo...","Dear Strong Bad,","You must be a very busy man.","You should think about a vacation.","Filled with crap,","BrothaCheese.","Oh, vacation, eh?","You know, I have been sittin at this computer for a long freakin' time.","And Strong Mad says I've been lashing out at The Cheat more often than usual...","Yeah, you know what?","I'm outta here.","DORKS!","Hey, you guys!","Just dropping you a line here from 'The Great Mound'.","I got two words for ya: false advertising.","There's nothing great about this mound, okay?","And another thing- there's nothing but old ladies hanging around this mound!","You know, wearing their muumuus and their tutus and all their Dainty McDainty crap...","Like... I don't like old ladies.","I don't even wanna see 'em.","Anyways, the mound was a big disappointment.","I'll write from my next destination.","Later!","Hey everybody.","Don't be fooled.","Downtown Pantsburg isn't anywhere near as fabulous as it appears in that photograph.","I mean, they don't even let you ride that bike!","In fact, it was, like, welded to that little house!","Anyways, I met some guys here, they were pretty cool, we hung out, y'know, made fun of this one girl...","pushed some guy into some mud...","We traded addresses and stuff and they say they're gonna come visit, but, you know how that ends up.","I'll never see 'em again.","Come to think of it, I probably should have taken some of their stuff.","Oh well.","That old highway's a-callin' my name, so, you'll hear from me soon.","Peace!","It's that clooooock...","Come on you guuuuuuys...","You need to check it on ouuuuuuuut...","It's that CLOCK!","I can't believe it!","Okay, the best thing about this postcard is if you look at the clock, that's the exact same time that I first laid eyes on the clock!","2:55, man.","And like, iddi—oh, wait, it still says... 2:55.","Okay, well, the clock is broken, but still!","It's about the best thing I've ever seen in my whole liiiiiife!",
    "Okay, now I got to bust a wicked solo.","Thank you, good night!","'Sup, everybody?","Here I am in Two Cars, Tennessee, and you know what?","I kinda miss you guys and your emails...","I can almost hear one of them now:","Dear Stong Bad, You are crap.","Crap is the best.","Everybody loves crap.","Crap is in the mix.","Crap is to the max.","How does Homestar pick stuff up if he's not wearing any Marzipants?","Crapfully crap, Monkey D, Seattle, Washington.","Ahh... okay!","I got my fix.","On to the next town!","Oh, and incidentally, I highly recommend Two Cars, Tennessee.","It's got a real happenin' arts and crafts scene.","Hey guys, just a quick one while I'm away.","So I visited Historic Over There.","Don't be fooled by the old-timey photograph— the place really looks like that.","Like, everything is tan and brown.","The sky?","Tan.","And the streets are paved with a little different shade of tan.","It was nothing but antique stores down there, like I couldn't find a single restaurant!","I have a sneaking suspicion the people in Over There eat antiques.","Yeah.","Screwed up.","There was one guy out there doing caricatures, though.","I stopped by and got one... of myself...","He made me...","A caric-ter... choor...","It was great.","Okay.","All this old Coca-Cola memorabilia is making me thirsty.","I'll talk at ya soon.","Hey!","Dorks!","Get offa me!","You stink!","Tee hee hee!","Oh man.","My legs don't even reach the pedals!","This is about as fun as Mr. Toad's Wild Ride...","But actually, that was pretty fun.","There's that part where you think you're going to hit the badger, and—what the?","Oh geez!","...Hey, coupons!",

    //41. invisibility
    "I'm hooome!","Okay, let's see here.","Don't need this anymore.","I don't need this anymore!","For behold...","The 386.","A spectacle of graphics and sound!","Okay, let's get to checking!","strong bad,","what would you do if you were invisable for one day????","sin studly17.","Well dumb name, this is something I've often thought about myself.","And I came to the conclusion that...","I don't really think being visible prevents me from doing whatever I want to do.","So I'd probably just do the kinda stuff I normally do.","You know, like, steal stuff...","My chocolates!","Come back, chocolates!","I didn't mean what I said...","...punch stuff...","Marzipan is late.","Oh, hey, guys!","Ooh! Owww!","Those things are bad for you.","...eat stuff...","and at the same time...","...watch stuff...","Pwa ha ha ha!","Survey says, you're an idiot!","Oh, hey, man.","Look, I'm sitting here, I'm just invisible, okay?","Hey! Brain-for-brains!","I'm right here!","The floating Swiss Cake Roll is talking to you!","Hey, no—","WAAAAAAAAAAAHHHHHHHHH!!!!","Ugh!","Nevermind.","Being invisible is not worth a face full of Strong Mad butt.","Ugh.","I feel like I need to take a shower.","I dunno when the last time he washed that singlet was.","Anyways.","Remember, kids!","Take your vitamins, pretend you're hilarious, and always, always, email Strong Bad.","Why Strong Bad? Why?","Remember the Duck Pond?","I thought we were a team.","Whatever, man. I can make it on my own.","386? More like three eighty SUCKS!","Tell the printer I'll miss her.","Yeah? Well someone on eBay loves me.","There's flies in me. It tickles.","My mind is going. I can feel it.","My mind is going. I can feel it.","My mind is going. I can feel it.","My mind is going. I can feel it.","My mind is going. I can feel it.","Fine, I'm gonna start giving away secrets.","Have you clicked on the 'O' in Message Bored?","Justin Bailey ****** ******","Oh jeez.","I think this is really it.","gasp.","wheez.","cough.","end of line.",

    //42. action figure **** where i started comparing "spoken as well"
    "Doo doo do doo, doo duh doo doo!","Hey Strong Bad,","If someone made a Strong Bad action figure, what kind of awesome stuff would it be able to do?","Kyle Rechsteiner","San Mateo, CA.","Camateos, Scamateos.","Oh man, Kyle.","My action figure would have it all.","First of all:","It'd look exactly like me...","...you know, in terms of his physique, and the relative size of his head to his body, it'd be exactly the same.","And of course I'd come armed to the teeth with my Chinese throwing croissant!","Then, I'd be able to shoot sparks from my mouth, you know like...","It'd make a noise like that.","And when you push down on my head, there'd be...BOOFFF!","Double Deuce action!","And then of course, you could take the head off, too, and there'd be a hole where you could pour like, motor oil, or whatever kinda junk you wanna put in there.","And then, turn out the lights...","Glow-in-the-dark abs, man!","Oh!","Oh!","And get it wet and you get SEVERE KNIFE FIGHT DAMAGE like magic appears!","But that's not all!","UH-OH!","Battle damage!","And finally, switch to the dispenser fist to ooze radioactive goo!","I think those things would sell like hotcakes, man.","Ooh!","Especially if they smelled like hotcakes!","Anyways, I tried to make one of my own one time and it didn't turn out as good as my imagination.","Basically all it has is...smells-like-peanut action.","I'm lookin' for some licensees.","Doo doo doooo!","Hey Homestar, get away from here!","Holy crap!",

    //43. little questions
    "All the ladies want to know, who's checkin' that email?","Was it Strong Bad?","Dear, Strong Bad!","Here is some little questions:","1. Has you some time play football?","2. How did you seen out when you was a baby?","3. How did you think you came's to seen out when you are wery old?","Viklas, Sweden.","Oh really?","Never would have guessed you weren't from around here.","Lessee here, what's the best way to answer this one...","For Viklas.","Hi?","Sup Viklas.","Prehaps!","I'm've was to make football often times.","I love football.","It's the best.","Play?","Know.","Oh, wait.","Are you asking about soccer?","Best football results twice again.","I hate soccer.","It's the worst.","2. Every age I have seen out as a baby.","I was one hot baby.","I think I has the solution: width times height.","All the girl babies were like, 'Check out that hot baby.'","3. As a wery old, I can fathom the scene to be with me.","I didn't know what you were talking about here.","Looking always as I ever did.","Hey, send me some of those Swedish fish.","It was not came's.","Ooh! And Swedish meatballs!","He borrowed mine.","That would be awesome.","Okay, Viklas, I hope that answers your questions.","I think we're on the same page.","Unfortunately, yours has a big F on it.","—Stark Dålig",

    //44. lures & jigs
    "I check e-mail from the front to the back, I said check e-mail from the front to the back, I said check...","Dear Strong Bad.","Dear Strong Bad?","Dear Str—","Hmm, I'll go with that one.","Dear Strong Bad,","When you go fishing, do you use any sort of special lure or jig to attract the fishs?","David Jacobus","Astoria, NY.","Say, Strong Bad, what type'a lure are you usin' dere?","Well, this morning, Coach, I've been mostly using this one:","Hey fish!","Hey fiish!","I'm gonna, I'm gonna recommend that you guys come up here in the boat.","We've got a, uh, a keg!","Of worms!","And, uh...phytoplankton!","Come on!","Anybody who's everybody is up in here!","I don't think that's gonna work with a stocked pond.","You got any type of jig you could try on there?","Oh, yeah! I got this jig!","Come on and get in the boat, fish!","Come on and get in the boat, fish fish!","Come on and get in the boat, fish!","Get in the boat!","Oh!","They got in the boat!","Fish fish!","Actually, David, it may surprise you to hear this but, uh...","I don't know anything about fishing, man.","You're welcome to try the jig thing if you want.","Though it might work better with the ladies.","You know, like,","Come on and come to my house, ladies!","Come on and come to my house, girls girls!","Actually, I don't really know anything about the ladies either.","I mean I do!","I mean—WHGT!","JGTH!","YES I'M AWESOME!","Whoa, look at that title screen!","Man, the 386 never ceases to amaze me!","INSTRUCTIONS.","-PRESS 'J' TO JIG.","-PRESS 'L' TO LURE.","Some fish respond to lures, others to jigs.","CATCH MORE FISH FOR MAXIMUM FUNTIME!","No way!","This is the pinnacle of graphics.","They're never gonna get any better than this.","I bet the sound's just as good, too!",

    //45. techno
    "It's the email, the email, what what, the email.","Hey Strong Bad, do you like techno at all? If you do, what kind.","Silent J.","Huh, that...","Very clever.","Well, its not really my style, but I heard a techno song one time that went like...","Doom doom doom doom doom doom doom doom.","And then this other part came in, and it was like...","Doodle-um-doom doodle-um-doom doodle-um-doom doodle-um-doom.","And then there's always some kinda high pitched noise, y'know?","Or like a siren that's like...","DOO-DA-DOO-DA-DIDDLE DOO-DA-DOO-DA-DIDDLE DOO-DA-DOO-DA-DIDDLE DOO-DA-DOO-DA-DIDDLE.","And of course they have to put in the obligatory old movie quote from some sci-fi movie.","It's like...","The system is down!","The system is down!","The system is down!","The system is down!","The Cheat is grounded!","We had that light switch installed for you so you could turn the lights on and off.","Not so you could throw light switch raves!","Now let's go break open that glowstick and pour it into Homestar Runner's Mountain Dew.","I heard they have to pump your stomach when you drink that stuff.",

    //46. your friends
    "Emaiiiiil...","WASSUP!","YOU ARE AWESOME.","I LIKE IT MOST WHENYOU HARM YOUR FRIENDS.","ANDREW.","Andrew, this is the best email I've ever received.","Let's get to work!","Some type of TV show...","Hows about this!","What the?","OW!","OW!","OW!","OW!","Close your eyes and hold out your hands.","I don't want to!","Put your head in here.","You got it!","AaAaAaAaAaAaA!!!","I'm savin' the best for last!","Hey, thanks for the chippies, Strong Bad!","Ahhh, just givin' the fans what they want!","You may notice I didn't do anything to the Poopsmith.","I figure the guy shovels crap for a living so his tolerance for pain's gotta be through the roof.","I was thinking about giving him a bath or something but, just the thought of that gave me the jibblies.","Here they come again.","The jibblie jibblies...",

    //47. new hands
    "Doo doo doo doo doo... email!","Doo doo doo doo doo.","Hey Strong Bad,","If you had both your hands removed at the wrists and could not have them replaced with prosthetic hands, what 2 things would you have them replaced with?","- Ryan.","Toronto.","Lemme think for a second, Ryan.","Ooh!","Ooh!","I got it!","One hand would have a bucket on it.","That way, I would always... have a bucket.","You know, for like, dumping oatmeal on stuff—","—for washing The Cheat—","—and like, dropping the occasional beat.","These peoples tried to fade me!","And also, I could sit on it when I get tired.","Sit right down on the bucket.","And the other hand would definitely be a bullhorn.","That way, everyone could hear all the important stuff I gotta say.","I am still awesome.","Seriously.","Hey, Coach!","Uh... I wasn't trying to fade you.","That wasn't me.","I don't know who those peoples were.","Now I know you were all expecting me to pick things like guitars and lazor guns...but I—","Aww, man!","Why didn't I pick guitars and lazor guns?","Bullhorn?!","Pfft!","Like having a bucket for a hand's gonna get me any chicks...","What was I thinking?",

    //48. ghosts
    "Boy, is it ever Monday!","Yo yo, Strong Bad!","Are there any ghosts in Strongbadia?","Your Favorite Cowboys,","Josh, John & Doug.","Nashville, TN.","Whoa.","Took all three of ya to come up with that one, huh?","You're some bright young men!","You know boys, cowboys, I've never really given the ol' kingdom a thorough ghost check.","The Cheat!","Meet me in the Strong Bad Cave!","Quizzical The Cheat noise.","Erm, well...meet me in the closet and, uh...we'll put on some costumes.","Okay, The Cheat, let's just turn on my ghost-detecting equipment here...see if we can't get any readings.","Hey Sign!","You haunted?","What about you, Tire?","Any ghosts?","Chinese food!","You a ghost?","IT'S THE GHOST OF GENERAL TSO!","Oh wait.","It's just grody and rotten.","The Cheat, will you please freaking clean up after yourself?","Oh well, looks like Strong Badia is ghost-free, proud to be.","Oh!","Uh... My old computer!","Umm... What's up, man?","Sure is one... spooky sound you're making there...","Ooh, lookit that!","Little...bad graphics ghost.","Hey, little guy...","Look, old computer.","Sorry I threw you out and everything but, uh...","The Cheat, um...","Chea-Chea-Cheat's got soccer practice, so uh...","Did you remember your cleats, The Cheat?","THROW THAT CHINESE FOOD AT HIM!","Have you seen the ghost of John?","Long white bones with the skin all go-o-o-one!","Whoo! whoooo! whooo!","Wouldn't it be chilly with no skin ooonnnn...?","Whoa, check it out.","It's like I'm the master of time and space in here."


];

    module.exports = transcripts;