let transcripts = [
    
    //1. some kinda robot
    "Oh, who is the guy that checks all his emails? That's me, Strong Baaad.","Dear Strong Bad,","Do you take your wrestling mask and boxing gloves off before you go to bed?","Sincerely, Abdi Larue.","San Diego, CA.","Well, that's a stupid question, Abdi.","Do you take off your face and hands before you go to bed?","And if so, are you some kind of robot?","And if so, what kind of powers do you have?","Do you use them for good, or for awesome?","Would you like to join forces?","I just happen to be the greatest criminal mind of our time.","Okay, until next time. Keep sending me your questions, and I will make fun of you... I mean, answer them.",
    
    //2. homsar
    "I'm gonna check my email all of the time, doo doo doo...","Hi Strong Bad,","If you hate Homsar so much, why don't you kill him?","-Vinnie C.","You know what, Vinnie? You're right. I'll be right back.","Hey, Homsar!","Uhdyeah, what ees eht, Stwong Baaaaayaad?","Oh man, Vinnie.","That feels so much better","Thanks a lot!","Okay, so until next time, keep sending me your questions, and I will keep making fun of your punctuation and spelling.","I mean, answer them.",
    
    //3. butt IQ
    "Checkin' my email, checkin' my email, checkin'-checkin'-checkin'-checkin' my email.","Dear Mr Bad,","How do you know if someone's butt is stupid?","I mean, is there like some kind of IQ test?","Crapfully yours,","Tyler.","Oh, come on Tyler!","Don't you remember your algebra, man?","It's called the Transitive Butt Property.","And it clearly states that the stupidity of somebody's butt is greater than or equal to the stupidity of that person's head.","So, take our friend Homestar Runner for instance.","Look at his stupid head!","Look at how stupid his head is.","Okay, so you can easily infer from this that because he has such a stupid head, that easily his butt is going to be at least as stupid if not stupider.","So there you have it.","Okay, so until next time, on a scale from one to awesome, I'm super great.",

    //4. homestar hair
    "I check the email once, I check the email twice, doo doo doo, doo doo doo...","Okay, let's see what we got here...","Homestar Hair.","downloading...","Home...star...Hair...?","What the...","Oh man!","I swear if I get another one of these freakin' 'Hairstyle Runners' from one of you guys, I'm gonna have to start busting some heads, okay?","I mean, how come you people never play my game, man?","I never get any Strong Libs in my email.","I mean, there's this whole game out there that's all for me that you guys can fill out, you know, and like, send me some hilarious crap or something.","Now you got me all cheesed off!","I'm gonna play some 'Temple of Apshai'.","Forget you guys.","Oh, my hit points are, like, inexcusable in this dungeon, man.","I need to find some elixir or something.",
    
    //5. making out
    "Checkin' emails is like the best thing I do.","Dear Strong Bad..,","Do you like making out?","Because my boyfriend won't.","Mostly because he's jealous of you.","I've tried the whole Peter Frampton thang, but nothing seems to work out.","Please help me Strong Bad...","Kissless in Santa Rosa.","Well, Kissless, you're going about it all wrong.","Frampton's not going to loosen anybody's lips.","If you really want to make out with this guy, you need to go straight to the master of make out rock himself... ME!","So here's what you do.","You wait til he comes home, then light a few candles and maybe have a glass of wine.","And then put on my hit single 'You're Really Ugly (But There's Nobody Cute Around).'","I'll tell you what, he'll be all over you like the King of Town on a Chinese buffet, man.","All right, so until next time send me more questions.","SEND ME MORE QUESTIONS!!!",

    //6. depressio
    "I check, you check, we all check for e... mail check... an email...","Dear Strong Bad,","Tell Strong Sad he is dumb and a crappy guy.","Your fan, Anthony.","from South Gate CA.","Hey, stupid! Do you know some guy named Anthony from South Gate?","Oh yeah. I was just making him this card—","—and gonna send him a hundred dolla—","Yeah, well he says you're dumb and a crappy guy.","Ohh...","Look Anthony, as much as I like insulting my stupid kid brother, I'm not your freaking message service, alright?","Next time, you email him yourself.","His email address is: depressio@homestarrunner.com.","Okay, so until next time, 'Everybody email that guy!'","'What guy?'","'ME!'","'Everybody email that guy!'","Hello there,","I hope your email wasn't full of awful, hurtful remarks like all the rest but I'll never know.","I stopped reading emails a long time ago and wish my brother would stop giving out my address.","Before you start making fun of me again, I'd like to share something with you.","I hope this puts us on the same page of this dusty, many volumed set of ever-changing encyclopedias we call Life.","Strong Sad is no longer accepting emails because you people kept signing me up for 'natural male enhancers.'","That, and the death threats weren't very cool either.","Leemee 'lone!",
    
    //7. halloweener
    "I am going to check my email.","Dear Strongbad,","I want to have the bestest halloween costume ever this year.","How can I make a strongbad costume?","With crap,","Ben from Ohio University.","Well Ben, I couldn't agree with you more.","You dress up like me this year and the ladies will flock to you like the Poopsmith to an overflowing toilet.","But I digress. Onto the costume...","We'll demonstrate on stupid over here.","Hello!","First, paint your head red.","Then, take your shirt off... to expose your manly chest.","Oh!","Next, get some boxing gloves,—","—or if you don't have boxing gloves, oven mitts will do.","Next, duct tape some aluminum foil—","—to some twine.","And finally, get your mom to make you a Strong Bad costume.","You'll be the belle of the ball.","I'm a belle!","Okay, so until next time, who put the 'ween' in 'Halloween'?","I don't know.","Probably you.","...you freakin' weirdo!",

    //8. brianrietta
    "I remember the time when I checked my email.","Dear Strong Bad,","Every time I watch a cartoon with you in it, I can't help but realize how incredibly gorgeous you are.","I love the way you walk around without your shirt on so confidently.","Anyways, I was wondering if you would like to go out sometime.","Give me a call, Pom-Pom has my number.","Hopefully yours, Brian.","Oh, well, Brian, maybe you and I could— uh— hey... BRIAN!?","What the crap?","Look, man.","Unless Brian is short for... Brianrietta or Brian-Sue or something like that, it's just not gonna work out between you and me, okay?","Sorry to crush your hopes and dreams, - Strong Bad.","Okay, so until next week...","1, 2, 3, email me!","1, 2, 4, email me more!",
    
    //9. i love you
    "I've carefully set aside this time for checking my email.","i love u.","-fhqwhgadshgnsdhjsdbkhsdabkfabkveybvf.","Look, fhqwgadshg...","Can i just call you fhqwhgads?","Look fhqwhgads, I'm sorry to say, but the feeling's not mutual.","Mainly because of your long freakin' name.","I mean in the time it took me to say your name, I coulda done all kinds of stuff.","Like paint a picture of a guy with a big knife.","Whoa, in fact, I'm gonna get started on that right now.","Oh yeah!","This is looking great.","I mean, I think I could probably sell this at like the arts and crafts fair, you know... to maybe some POWs, or, like, somebody's dad...",

    //10. trevor the vampire
    "I'm totally checking my email.","Total, man.","Hi strong bad.","This is Trevor from Hampden Maine and I was wondering if you could teach me how to be as awesome as you.","I am a vampire and...","And what?","That's it?","I'm a vampire and here's a million dollars...","or I'm a vampire and here's your own spaceship...","I mean what the f-","Oh no, I get it.","THEY GOT HIM!!!","Somebody stuck him with a stake through the heart!","Oh, this is so sad!","Oh Trevor, I pine for you.","Hi, everybody.","In memoriam of poor Trevor, let's go back and revisit a few of my favorite Trevor memories.","This is Trevor from Hampden Maine and I was wondering if you could teach me how to be as awesome as you.","Oh, that was great. And who could forget this one?","I am a vampire and...","And what? That's it?","Ah, we sure had some great times Trevor.","In Memoriam -Trevor-","I'm gonna miss you, bro.",

    //11. i rule
    "Email, grumble grumble, email, grumble...","If you are so evil, how come you don't rule the world or at least some kind of field?","Mike, UK.","What are you talking about, Mike, UK?","I mean I've totally ruled that field out behind the dumpsters since like diaper school, man.","Aaaah, my kingdom continues to flourish. Uh, carry on, everyone.","Hey!","The Cheat!","What, you wanna get banished? Don't touch that!","What're you standing around for, man?","Don't you have, like, some of my bidding to do?",

    //12. credit card
    "Initiate email check in five, four, three, two, one.","Dear Mr. Bad,","We regret to inform you that your credit card has expired.","To keep your account, we will need you to send your old credit card number and expiration date, as well as a new one so we can make the change.","We promise we are real and not just trying to steal your money.","John, and some other people who aren't scam artists.","Whoa, this sounds pretty serious. I know just what to do.","Just a little of this...","Ooh, maybe a dash of that...","Okay, let's see what we got here...","Dear Superfied Credit Union,","You've got the same e-mail address as my friend Strong Bad!","Anyway, here's my credit card information:","That was too easy, man.","Well, it looks like Homestar is about to make a little contribution to the Lots of Awesome Stuff for Strong Bad Fund.","Gimme one of these...","A couple of these...","Oh, everybody needs one of these...","Oh, this thing, I gotta have that...",

    //13. i she be
    "Email, dud-duh-doo-duh-dud-duh, dud-duh-doo-duh-dud-duh...","hey my name is great looking girl strong bad!","i she be your girlfriend.","Uh...","Hey!","My name is Strong Bad, great looking girl!","I he be your boyfriend.","Okay, seriously. All i gotta say about this is...","GET IN LINE SISTER!!!","I mean, do you know how many freakin emails I get like this a DAY?","From ladies with proper grammar?","I mean come on!","A guy's gotta have some standards right?","But, I do feel kinda sorry for you, so I won't let your email go to waste.","Okay, so tune in next time: Same Strong Bad time, same Strong Bad channel.","are you around, clown?","sure am, sam.","LOL!!! :-*.","i want us to meet in person.","OMG!","where?","the food court?","sbarro.","8pm.","whatta you look like?","6ft tall.","buff.","big red 'M' on my chest.","no neck.","can't wait.","L8r.",

    //14. duck pond
    "Must... check... email...!","dear strong bad,","do you ever feed the ducks?","personally i think feeding the ducks is the greatest thing in the world.","what are your thoughts on this subject?","your friend,","ron kiwi.","Unfortunatley, Mr. Kiwi, there are no ducks by my house.","But I do have a pretty sweet duck pond simulator for my computer.","Check it out, man.","Wow, you're right, Ron.","This is the greatest thing in the world.","I mean it's like I'm right there at the pond.","Come here, ducky.",

    //15. the basics
    "Everybody... check your email...","Dear strong bad,","how do you do it .","teach me some of your trick's.","With crap,","T.J.","Well, I mean I can't tell you all of them TJ, But, you know, there's the basics.","I mean, like if somebody's like, 'Hey! Are you listening to me?'","You say, 'Yes,' but you know you're not really listening.","Um, then there's the one where you say, 'Hey! Look over there.'","And when they turn their head, you know there's nothing there and you pour some Coke down their shirt.","And this one is a little amateur, but it has worked for me in the past.","You know, you bet somebody a hundred 'bucks', and if they win, you know, you'll... you give them like a hundred kicks in the butt and you say, you call that a buck.","I mean, I don't know, somebody invented that...and...it works pretty good.","You get to kick somebody.","But everyone has a different taste, you know?","Develop your own style, TJ.","Reach down inside yourself and pull out something...y'know, not like...organs.","You know what I mean.","Anyways, email...","Oh, there'll be another one next week..."
];

    module.exports = transcripts;